name: kiska
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^1.1.6
  iconsax: ^0.0.8
  google_nav_bar: ^5.0.6
  get: ^4.6.6
  carousel_slider: ^5.0.0
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
  badges: ^3.1.2
  http: ^1.2.2
  lottie: ^3.1.2
  google_sign_in: ^6.2.1
  provider: ^6.1.2
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.3.2
  loading_animation_widget: ^1.3.0
  shimmer: ^3.0.0
  custom_navigation_bar: ^0.8.2
  flutter_screenutil: ^5.9.3
  bounce: ^1.0.2
  animations: ^2.0.11
  phonepe_payment_sdk: ^2.0.3
  crypto: ^3.0.6
  flutter_touch_ripple: ^2.2.2
  flutter_native_splash: ^2.4.3

  smooth_page_indicator: ^1.2.0+3
  flutter_launcher_icons: ^0.14.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter_native_splash:  # Background color of the splash screen
  color: "#008080"
  image: assets/images/logos/kiska.png

  android_12:
    image: assets/images/logos/kiska.png
    color: "#008080"
  

flutter_icons:
  android: true       # Enable Android app icon generation
  ios: true           # Enable iOS app icon generation
  image_path: assets/images/logos/kiska.png
  adaptive_icon_background: "#ffffff"  # Background color for Android adaptive icon
  adaptive_icon_foreground: assets/images/logos/kiska.png  # Foreground image
    


flutter:
  uses-material-design: true
  assets:
    - assets/icons/ 
    - assets/images/onboarding_images/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/user/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
